// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradeOffStackAPI.Data;
using TradeOffStackAPI.Models;

#nullable disable

namespace TradeOffStackAPI.Migrations
{
    [DbContext(typeof(AssetDbContext))]
    [Migration("20260610202709_AddSaaSArchitecture")]
    partial class AddSaaSArchitecture
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TradeOffStackAPI.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<AuditAction>("Action")
                        .HasColumnType("audit_action")
                        .HasColumnName("Action")
                        .HasAnnotation("Relational:JsonPropertyName", "action");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "entity_type");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("jsonb")
                        .HasAnnotation("Relational:JsonPropertyName", "old_values");

                    b.Property<DateTime>("PerformedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasAnnotation("Relational:JsonPropertyName", "performed_at");

                    b.Property<Guid?>("PerformedById")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "performed_by_id");

                    b.HasKey("Id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.HasKey("Id");

                    b.ToTable("departments", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "department");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<AssetCategory>("Category")
                        .HasColumnType("asset_category")
                        .HasColumnName("Category")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DepreciationMethod>("DepreciationMethod")
                        .HasColumnType("depreciation_method")
                        .HasAnnotation("Relational:JsonPropertyName", "depreciation_method");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "image");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "image_url");

                    b.Property<string>("ImageUrlHttps")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "image_url_https");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "price");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "purchase_date");

                    b.Property<decimal>("SalvageValue")
                        .HasColumnType("numeric(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "salvage_value");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "serial_number");

                    b.Property<AssetStatus>("Status")
                        .HasColumnType("asset_status")
                        .HasColumnName("Status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<int>("UsefulLifeYears")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "useful_life_years");

                    b.Property<DateTime?>("WarrantyExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "warranty_expiration_date");

                    b.HasKey("Id");

                    b.ToTable("equipments", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "equipment");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.EquipmentLicense", b =>
                {
                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "equipment_id");

                    b.Property<Guid>("SoftwareLicenseId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "software_license_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "assigned_at");

                    b.HasKey("EquipmentId", "SoftwareLicenseId");

                    b.HasIndex("SoftwareLicenseId");

                    b.ToTable("equipment_licenses", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "equipment_licenses");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.MaintenanceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "completed_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "equipment_id");

                    b.Property<MaintenancePriority>("Priority")
                        .HasColumnType("maintenance_priority")
                        .HasColumnName("Priority")
                        .HasAnnotation("Relational:JsonPropertyName", "priority");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "requested_by_id");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "scheduled_date");

                    b.Property<MaintenanceStatus>("Status")
                        .HasColumnType("maintenance_status")
                        .HasColumnName("Status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<string>("TechnicianNotes")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "technician_notes");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UserId");

                    b.ToTable("maintenance_requests", (string)null);
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "approved_at");

                    b.Property<Guid?>("ApproverId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "approver_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "end_date");

                    b.Property<Guid>("EquipmentId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "equipment_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "notes");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "rejection_reason");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "return_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "start_date");

                    b.Property<ReservationStatus>("Status")
                        .HasColumnType("reservation_status")
                        .HasColumnName("Status")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UserId");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.SaaSAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "assigned_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasAnnotation("Relational:JsonPropertyName", "is_active");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "last_login_date");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "subscription_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "user_id");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("SaaSAssignments");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.SaaSProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "contact_email");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "website_url");

                    b.HasKey("Id");

                    b.ToTable("SaaSProviders");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.SaaSSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "billing_cycle");

                    b.Property<decimal>("CostPerSeat")
                        .HasColumnType("numeric")
                        .HasAnnotation("Relational:JsonPropertyName", "cost_per_seat");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "plan_name");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "provider_id");

                    b.Property<DateTime?>("RenewalDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "renewal_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "status");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "total_seats");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("SaaSSubscriptions");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.SoftwareLicense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "expiration_date");

                    b.Property<string>("LicenseKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasAnnotation("Relational:JsonPropertyName", "license_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasAnnotation("Relational:JsonPropertyName", "price");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "total_seats");

                    b.HasKey("Id");

                    b.ToTable("software_licenses", (string)null);

                    b.HasAnnotation("Relational:JsonPropertyName", "software_license");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasAnnotation("Relational:JsonPropertyName", "department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasAnnotation("Relational:JsonPropertyName", "is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasAnnotation("Relational:JsonPropertyName", "last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasAnnotation("Relational:JsonPropertyName", "phone_number");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "profile_image");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "profile_image_url");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("Role")
                        .HasAnnotation("Relational:JsonPropertyName", "role");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.EquipmentLicense", b =>
                {
                    b.HasOne("TradeOffStackAPI.Models.Equipment", "Equipment")
                        .WithMany("EquipmentLicenses")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradeOffStackAPI.Models.SoftwareLicense", "SoftwareLicense")
                        .WithMany("EquipmentLicenses")
                        .HasForeignKey("SoftwareLicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("SoftwareLicense");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.MaintenanceRequest", b =>
                {
                    b.HasOne("TradeOffStackAPI.Models.Equipment", "Equipment")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeOffStackAPI.Models.User", null)
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("UserId");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.Reservation", b =>
                {
                    b.HasOne("TradeOffStackAPI.Models.Equipment", "Equipment")
                        .WithMany("Reservations")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TradeOffStackAPI.Models.User", null)
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.SaaSAssignment", b =>
                {
                    b.HasOne("TradeOffStackAPI.Models.SaaSSubscription", "Subscription")
                        .WithMany("Assignments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.SaaSSubscription", b =>
                {
                    b.HasOne("TradeOffStackAPI.Models.SaaSProvider", "Provider")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.User", b =>
                {
                    b.HasOne("TradeOffStackAPI.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.Equipment", b =>
                {
                    b.Navigation("EquipmentLicenses");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.SaaSProvider", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.SaaSSubscription", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.SoftwareLicense", b =>
                {
                    b.Navigation("EquipmentLicenses");
                });

            modelBuilder.Entity("TradeOffStackAPI.Models.User", b =>
                {
                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
